### ISSUE TITLE
"Digital PUL" link should clear language selection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1153]
Expected:
The DPUL front page search box hint should say "search"

Actual:
Under some circumstances it may use a different i18n term.

Replicate:
Go to an exhibit with language options (e.g. https://dpul.princeton.edu/chilean_photographs) and select a language, then click the "Digital PUL" link at the top.

Implementation:
Currently it keeps the locale parameter and it probably shouldn't.

Initial report:
Tested when signed in and signed out. Search terms should be English unless specified otherwise by user  in individual exhibitions with language options activated.

![Screen Shot 2021-10-20 at 11 52 05 AM](https://user-images.githubusercontent.com/45043014/138127602-ef2429cc-c52c-4847-9653-01bddc3f9895.png)

**Comment by m-ichelleliu** [comment]
I'm thinking that changing the entire website language isn't feasible since we don't have enough translations in place. Instead, since we want to keep the language change limited to the scope of the current exhibit, and Anna and I were brainstorming for UI designs for the language dropdown to clarify that. This has been my favorite so far but we're still working on it. ![image.png](https://images.zenhubusercontent.com/62e3ec553e723055ba58287d/36319437-abf7-42b5-8ac8-b5ee7f8790c8)
