### ISSUE TITLE
Reindexing Slavic items is throwing a "405 Not Allowed"

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1292]
### Summary
When I go to https://dpul.princeton.edu/slavic/dashboard, click on "items" and attempt to reindex items from the button on the items page, it throws a 405 after a couple of minutes. I have attempted this twice. Recent indexing activity shows 2 attempts were not yet started, 0 items indexed. 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
No hard deadlines. This was discovered while I was indexing each exhibit individually, due to an issue with batch reindexing of DPUL (see #1291 ). 

### Priority recommendation

- [x] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked_
If the site cannot be reindexed from a global action for DPUL or within the site itself, we cannot be sure the exhibit is displaying all items from figgy for that exhibit. This may be rectified once #1291 is addressed?

### Expected behaviour
When I click on "Reindex Items" I expect (after a period of time) for a blue bar to come up stating that "reindexing all resources" has commenced, followed by a status bar that gives the total item number, the items in the midst of being reindexed and a percentage of how complete the task is. 
### Actual behaviour
When I click on "Reindex Items", after a period of time it takes me to a "405 Not Allowed" page.
### Steps to reproduce behaviour

- Go to: https://dpul.princeton.edu/slavic/dashboard
- Click on "Items"
- Click on "Reindex Items"
- wait.....

### Screenshots
![Screen Shot 2022-02-01 at 10 18 10 AM (2)](https://user-images.githubusercontent.com/45043014/151997736-fab25485-6708-4b9f-957e-3e5a897d81dd.png)
![Screen Shot 2022-02-01 at 10 18 30 AM (2)](https://user-images.githubusercontent.com/45043014/151997763-5f0df3d1-baad-4b88-80b6-4386e63f9174.png)

**Comment by kelea99** [comment]
Changed urgency to ASAP. See @hackartisan  above and now 0 items have indexed for the site.

**Comment by hackartisan** [comment]
I found a 499 in the logs from this request. https://app.datadoghq.com/logs?query=service%3A%28dpul%20OR%20nginxplus%20OR%20figgy%20OR%20solr%29&context_event=AQAAAX612zbI9nBRNQAAAABBWDYxMnpiYkFBQkk5R2xxamU3RUd3QmY&event=&index=&stream_sort=desc&viz=&from_ts=1643728547853&to_ts=1643728548454&live=false

I'm not sure how that ended up showing as a 405. But this is an nginx error screen, not a rails error screen, which suggests that the problem happened between servers rather than in the application.

I have clicked reindex again and did not receive an error. There is a lot in the queue, though, so it will be a while.

**Comment by hackartisan** [comment]
Here's the story from more logs examination:

- the load balancer sent the request to dpul, waited around for a response
- nginx on the dpul machine received the request, routed, it, and waited for rails to respond
- the app started fetching the manifest from figgy
- nginx on the dpul machine didn't get a response quickly enough, and returned a 499
- the load balancer served a 405 error (still not sure why a 405)
- the app got the manifest and enqueued the job, returning a 302 redirect to... nobody because the nginx service wasn't really listening anymore

The job was enqueued at 9:15, 10:15, and 12:02. 2 of them are still on the queue but one was performed between 11:07 and 11:45 (ironically right before the last one was enqueued).
