### ISSUE TITLE
Unpublished Lapidus_pamphlets exhibit is raising a server error

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul#1303]
Does this collection need to be re-indexed?

```
[DPUL/production] ActionView::Template::Error: key not found "tile_source_ssim"
```

## Backtrace

    line 25 of [PROJECT_ROOT]/app/models/solr_document.rb: fetch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/62921650)

**Comment by tpendragon** [comment]
@kelea99 https://dpul.princeton.edu/lapidus_pamphlets is broken. How fast does this need fixed?

**Comment by kelea99** [comment]
@tpendragon and @eliotjordan the unpublished Lapidus-pamphlets DPUL site is not going to be used. Everything has been added to the live Lapidus dpul site that is functional: https://dpul.princeton.edu/lapidus.  However, navigating to the "Lapidus pamplets" collection within that live site via the link within the metadata returns the same error as the DPUL collection (for obvious reasons).  For the time being, I will not make the collection link visible in the metadata and the search facet for collections is not visible. 
**Proposal:**
-  Now: Delete the unpublished dpul site for lapidus_pamphlets and if we have to rebuild, we will do so later. 
-  Before 31 May, 2022: Research why the collection link is broken so that we can have it back up and running by June.  The Collection is to be completed in DPUL in June, 2022.
- Troubleshoot: I can always create a new collection tag in Figgy, batch tag the lapidus pamphlets collection items to it, and delete the "Lapidus Pamphlets" collection.

**Comment by hackartisan** [comment]
That exhibit isn't needed and we will delete.
