### ISSUE TITLE
Treasures of the East Asian Library Reindex issues

### ISSUE THREAD

**Issue by kelea99** [pulibrary/dpul#1488]
### Summary
@tventimi reported not seeing new items appearing in this collection after making them complete in Figgy on the morning of Wednesday, Nov. 22. I was able to get them in by resaving/completing in figgy. as of today, the collection is still having rendex issues.

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
issue is stoppind dpul access to materials.
### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked.  Add "Sudden Priority" and "Maintenance/Research labels_
this is stopping access to materials in DPUL. @tventimi - is there an immediate deadline? is this asap request?

**Comment by tventimi** [comment]
Just an update on this issue:  I have gradually been adding items to this collection, and some appear in DPUL right away, others not even after several days.  As of today, I have marked reels 1-136 as complete in Figgy, and 20 of them are missing in DPUL: 100, 102-106, 108, 110-112, 117, 118, 120, 121, 124, 125, 128, 130, 132, and 134.  To me, there is no obvious pattern to which reels appear in DPUL and which do not.

**Comment by kelea99** [comment]
Making a new ticket to check out DPUL-Figgy sync auto-reindexing in general, @hackartisan . got another similar issue as above but for ephemera folders. I know he had a problem in the past, so ill look for that closed issue to refer to.

**Comment by tventimi** [comment]
I solved the issue for this particular series just by saving all of the missing reels again, though for some of them it look several tries.

**Comment by hackartisan** [comment]
Today I discovered that one of our DPUL machines was not able to connect to redis. That explains this error perfectly: Any time the workers on that box picked up the updates from Figgy, they tried to enque the index update but it got dropped because it couldn't enqueue the job. So sometimes it would have worked (when the worker that could connect picked up up) and sometimes it didn't (when the worker with connection issues picked it up). The redis connection is now fixed and that should resolv this issue.
