### ISSUE TITLE
SMTP not configured for sending emails.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul#705]
> Reported by Fernando via Snap. Steps to reproduce:
  Bookmark an item on the search results page
  View bookmarks and click "Email"
  Fill out form and submit the form.
  The error message "Network Error" is displayed.

See #704 for original issue.

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/59851660)

There's documentation at https://github.com/pulibrary/pul-the-hard-way/blob/main/services/smtp-mail-server.md

**Comment by hackartisan** [comment]
I just emailed lsupport to get added the dpul prod boxes added to the allow list. The setup for allowing email to princeton email addresses is well-defined and we will do that first; it may be all we need.

For sending email to non-princeton email addresses, the process is not well-defined. I can work on clarifying this but we should determine whether we need it, maybe as part of evaluating the success of the work done for princeton email addresses. A couple of considerations:
- You can't log into DPUL without a network account
- The link to the bookmarks page only shows if you are logged in
  - Even if we changed this, bookmarks wouldn't persist beyond a session, so there could be some usability work to make sure folks without network accounts understand its impermanence.
  - If we don't change it, still may be some usability work to do here because a person without a network account can create bookmarks but not view them.
- I'm not sure what the implications are for our collaborators with proxy network accounts.

**Comment by kelea99** [comment]
@hackartisan , if the non-princeton.edu accounts for collaborators are university sponsored, does that make any difference to the synopsis above? 

Regarding determining whether or not we need support for sending email to non-princeton addresses:  Since Fernando is the primary stakeholder to ask about bookmarks, it might be good to start with looking at how the LAE site is configured and then go from there?  Is it set up to mail bookmarks to whomever?

**Comment by hackartisan** [comment]
@kelea99 the question about the sponsored accounts is what I'm not sure about. We may need to try it with a test account.

Great idea to get feedback from Fernando and look at LAE.

Since I got SMTP configured I'm closing this ticket. I created #1256 as a follow-up since the urls that come through in the email are not right. We can create more tickets if needed based on what we see with LAE.
